### ISSUE TITLE
Warning on launch

### ISSUE THREAD

**Issue by Dwarfknight** [BerndiVader/mmArmorStandAnimator#1]
I am new to plugins and may have missed a step or made some other mistake. I copied the jar file into plugins and i also created a Anims folder in Mythic mobs and copied over the example files for the mob, skills , and animations and put them in their respective folder. Upon launch I get 

WARN: [MythicMobs] Could not find AbstractSkill animatorskill 

I can use the mythic mobs mobs no problem but I cannot summon the moonwalker or any of the animator example mobs.

**Comment by BerndiVader** [comment]
Hello! Sorry for the late response. For me it looks like you have copied the yamls to some wrong places. Grab alle the files and folders from `mmArmorStandAnimator/MythicMobs/` and copy them into `plugins/MythicMobs/` on your servers folders. Restart the server or reload and it should work.
