### ISSUE TITLE
spaming worng message

### ISSUE THREAD

**Issue by q27484092** [BerndiVader/mmArmorStandAnimator#4]
java.lang.NullPointerException: null
[19:35:19 WARN]: [AnimatorStands] Task #82925 for AnimatorStands v0.470a generated an exception
java.lang.NullPointerException: null
[19:35:19 WARN]: [AnimatorStands] Task #82925 for AnimatorStands v0.470a generated an exception

and

![image](https://user-images.githubusercontent.com/46105402/50398737-e9d3f280-07b4-11e9-97a4-10371fdb52dd.png)

**Comment by q27484092** [comment]
from a Taiwan server sorry for bad English
i love this plugin :D

**Comment by q27484092** [comment]
With 4.6 version mythicmob

**Comment by BerndiVader** [comment]
Hello! Sorry for late response. This happens if you reload the animatorstand at runtime by using plugins like plugman.
